title: Platform Engineering Hub
description: "Exploring the World of Internal Developer Platforms"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Site Settings
locale: "en-US"
subtitle: "Building Better Developer Experiences"
name: "Chan Nyein Ko Ko"
url: "https://channyeinkoko.github.io"
repository: "channyeinkoko/channyeinkoko.github.io"

# Site Author
author:
  name: "Chan Nyein Ko Ko"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Platform Engineering Enthusiast"
  location: "Sydney, Australia"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/channyeinkoko"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/channyeinkoko"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
